[package]
name = "atlas-siphash"
version = "0.1.0"
authors = ["nblock <nblock@nblock.dev>"]
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
atlas-common.path = "../atlas-common"
siphasher = "1"

[lints]
workspace = true
